# version: '3.8'
# name: 'cloud_wave'
# services:
#   success:
#     image: ubuntu:22.04
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - sleep infinity
#     networks:
#       private: {}
#     volumes:
#       - anonymous:/anonymous
#       - named:/named
#       - external:/external
  

# networks:
#   private:

# volumes:
#   anonymous:
#   named:
#     name: "named_volume"
#   external:
#     name: "external"
#     external: true

version: '3.8'
name: 'cloud_wave'
services:
  success:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - sleep infinity
    networks:
      private: {}
  fail:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command: 
      - -c
      - sleep fail
    networks:
      private : {}
  

networks:
  private:

