#docker-compose.yaml
version: '3.8'
name: 'network-across-project-1'

services:
  server:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - apt-get update && apt-get upgrade && apt-get install -y curl && sleep infinity
    networks:
      across_project:
        aliases:
          - main
  
networks:
  across_project:
    external: true